### ISSUE TITLE
Um comando faltando no manual

### ISSUE THREAD

**Issue by guilhermegoulart1** [EngajamentoFlow/unoapi#1]
Olá pessoal. 

No vídeo a um comando nano .env na pasta /home/chatwoot/chatwoot,  para adicionar a linha:

WHATSAPP_CLOUD_BASE_URL=http://localhost:9876

Não está constando no manual.

**Comment by cwmkthubconnect** [comment]
Foi adicionado muito obrigado

Agradecemos por colaborar
